FROM centos

RUN yum -y install epel-release && \
  yum -y install \
   curl \
   git
   
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
RUN git clone https://github.com/integer32llc/parity-setup.git
RUN cd parity-setup && \
    export PATH=$PATH:/root/.cargo/bin &&\
    cargo build --release

RUN mkdir /parity
WORKDIR /parity

EXPOSE 30300 8540 8180 8080

ENV refresh_on 29 Jul 2017

COPY . /parity/

VOLUME /parity
