version: '2'
services:
  parity:
    image: parity
    build:
      context: .
      dockerfile: Dockerfile.run
    network_mode: "host"      
    environment:
      - NODENAME=${MACHINE}
    ports:
      - 30300:30300
      - 8540:8540
      - 8180:8180
      - 8080:8080
    command: ${DC_COMMAND}


